# Generated by Django 5.0.6 on 2024-06-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hasil_Kategori',
            fields=[
                ('id_hasil_kat', models.AutoField(primary_key=True, serialize=False)),
                ('words_gini_score', models.FloatField(default=None, null=True)),
                ('bluelinks_gini_score', models.FloatField(default=None, null=True)),
                ('char_gini_score', models.FloatField(default=None, null=True)),
                ('words_mean', models.FloatField(default=None, null=True)),
                ('bluelinks_mean', models.FloatField(default=None, null=True)),
                ('char_mean', models.FloatField(default=None, null=True)),
                ('words_median', models.FloatField(default=None, null=True)),
                ('bluelinks_median', models.FloatField(default=None, null=True)),
                ('char_median', models.FloatField(default=None, null=True)),
                ('words_std', models.FloatField(default=None, null=True)),
                ('bluelinks_std', models.FloatField(default=None, null=True)),
                ('char_std', models.FloatField(default=None, null=True)),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.kategori')),
            ],
        ),
    ]
