# Generated by Django 5.0.6 on 2024-06-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id_artikel', models.IntegerField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('word_count', models.IntegerField()),
                ('bluelinks_count', models.IntegerField()),
                ('char_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artikel_Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('nama_kategori', models.CharField(max_length=255)),
                ('subcategories', models.BooleanField(default=None, null=True)),
                ('id_artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel.artikel')),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.kategori')),
            ],
        ),
    ]
